name: pyqt5-runtime-core22
version: '22.04'
summary: PyQt5 runtime stack based on core22.
description: This snap is to be consumed by various PyQt5 apps which uses Qt 5.15+ Qt provides C++ classes and QML types for rendering GUI.
grade: stable
confinement: strict
base: core22

architectures:
  - build-on: amd64

package-repositories:
  - type: apt
    formats: [deb]
    components: [main]
    suites: [focal]
    key-id: C65D51784EDC19A871DBDBB710C56D0DE9977759
    url: https://ppa.launchpadcontent.net/beineri/opt-qt-5.15.4-focal/ubuntu

slots:
  pyqt5-runtime-core22:
    interface: content
    read:
      - /

parts:
  platform:
     plugin: nil
     stage-packages:
       - adwaita-icon-theme
       - dmz-cursor-theme
       - gnome-themes-standard
       - gsettings-desktop-schemas
       - libdb5.3
       - libgdk-pixbuf2.0-0
       - libglib2.0-0
       - libglu1-mesa
       - libslang2
       - libxkbcommon0
       - light-themes
       - locales-all
       - python3-pyqt5
       - qt5-gtk-platformtheme
       - shared-mime-info
       - fonts-ubuntu
       - qt5-image-formats-plugins
       - xdg-user-dirs
       - samba-libs
       - ffmpeg
       - mpv
       # QWebEngine and its dependencies
       - qt515webengine
       - qt515webchannel
       - qt515declarative
       - qt515quickcontrols
       - qt515quickcontrols2
       - qt515svg
       - libnss3  # For SSL/certificates
       - libxss1
       - libasound2
       - libevent-2.1-7
       - libjsoncpp25
       - libminizip1


  cleanup:
    after:
      - platform
    plugin: nil
    override-prime: |
      cd usr/share
      rm -rf apport bash-completion bug doc doc-base lintian man pam-configs pkgconfig upstart zsh
