name: pyqt5-runtime-core22
version: '22.04'
summary: PyQt5 runtime stack based on core22.
description: This snap is to be consumed by various PyQt5 apps which uses Qt 5.15+ Qt provides C++ classes and QML types for rendering GUI.
grade: stable
confinement: strict
base: core22

architectures:
  - build-on: amd64

slots:
  pyqt5-runtime-core22:
    interface: content
    read:
      - /

parts:
  platform:
     plugin: nil
     stage-packages:
       - adwaita-icon-theme
       - dmz-cursor-theme
       - gnome-themes-standard
       - gsettings-desktop-schemas
       - libdb5.3
       - libgdk-pixbuf2.0-0
       - libglib2.0-0
       - libglu1-mesa
       - libslang2
       - libxkbcommon0
       - light-themes
       - locales-all
       - python3-pyqt5
       - qt5-gtk-platformtheme
       - shared-mime-info
       - fonts-ubuntu
       - qt5-image-formats-plugins
       - xdg-user-dirs
       - samba-libs
       - ffmpeg
       - mpv
       - python3-pyqt5.qtwebengine
       - libqt5webenginecore5
       - libqt5webenginewidgets5
       - libqt5webengine5
       - qtwebengine5-dev
       - libnss3
       - libxss1
       - libasound2
       - libxtst6
       - libgbm1
       - libvulkan1
       - libminizip1
       - libevent-2.1-7
       - libjsoncpp24
       - libre2-9
       - libsnappy1v5
       - libwebpdemux2
       - libxslt1.1
       - libhyphen0
       - libopus0
       - libvpx6
       - libharfbuzz-icu0
       - liblcms2-2
       - libopenjp2-7
       - libjbig0
       - libjpeg-turbo8
       - libtiff5
       - libwebp6
       - libwebpmux3

  cleanup:
    after:
      - platform
    plugin: nil
    override-prime: |
      cd usr/share
      rm -rf apport bash-completion bug doc doc-base lintian man pam-configs pkgconfig upstart zsh
